---
- name: Ubuntu install docker
  when: ansible_distribution == "Ubuntu"
  become: true
  block:
    - name: Ubuntu dependencies
      apt:
        name: 
          - ca-certificates
          - curl 
          - git
        state: latest
        update_cache: true

  #GPG keys
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

  #Repo for apt
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

  #Docker!
    - name: Ubuntu install docker
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

