user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;
load_module modules/ngx_http_image_filter_module.so;

events {
	worker_connections 1024;
}


http {
	root /app;

	server {
		listen 80;
		return 301 https://$host$request_uri;
	}
	
	upstream redblue {
		zone redblue_zone 64k;
		#state /etc/nginx/upstream_state.conf; Увы, только премиум подписка
        	server sklknn.ddns.net:8000;
        	server sklknn.ddns.net:8001;
	}
	

	log_format redbluelog '$server_name to: $upstream_addr [$request]';
	access_log /etc/nginx/access.log redbluelog;

	server {
		listen 443 ssl;
		server_name sklknn.ddns.net;
		ssl_certificate /etc/letsencrypt/live/sklknn.ddns.net/fullchain.pem;
		ssl_certificate_key /etc/letsencrypt/live/sklknn.ddns.net/privkey.pem;
		
		root /app;

		location /music/ {
			add_header Content-disposition "attachment; filename=song.mp3";

			try_files $uri /music/coolsong.mp3;
		}

		location /info.php/ {
			proxy_pass http://127.0.0.1:8080;
		}

		location /apache/ {
			return 301 http://$host:8081/;
		}

		location /redblue/ {
			proxy_pass http://redblue/;
		}

		location ~ \.png$ {
			add_header Content-Type "image/png";
		}

                location ~ \.jpe?g$ {
			image_filter rotate 180;
                }

	}
        include /etc/nginx/sites-enabled/*;	
}

