server {
	listen 8000;
	server_name sklknn.ddns.net;

        root /app/red;

	location / {
	
	}
	
}

server {
        listen 8001;
	server_name sklknn.ddns.net;

        root /app/blue;

	location / {
	
	}

}
